require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

# スタイル設定
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

# レイアウト設定
Layout/LineLength:
  Max: 120

Layout/EmptyLineAfterGuardClause:
  Enabled: true

# メトリクス設定
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

# レールズ固有の設定
Rails/FilePath:
  EnforcedStyle: arguments

Rails/HasManyOrHasOneDependent:
  Enabled: true

# RSpec設定
RSpec/DescribeClass:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5